const assert=require('node:assert/strict'),C=require('../NaiwaRunner/Web/core.js');let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}function fresh(){const r=new C.Run(()=>.5);r.start();r.objects=[];r.spawnAt=1e6;return r;}
test('lane boundaries and pause freeze',()=>{const r=fresh();for(let i=0;i<5;i++)r.action('left');assert.equal(r.lane,-1);r.pause();r.tick(.05);assert.equal(r.distance,0);assert.equal(r.action('right'),false);r.resume();r.tick(.05);assert(r.distance>0);});
test('jump clears low obstacle and slide clears bar',()=>{for(const type of ['low','bar']){const r=fresh();r.object(type,0,10);r.action(type==='low'?'jump':'slide');for(let i=0;i<30;i++)r.tick(.016);assert.equal(r.chase,0);}});
test('collision warning then game over',()=>{const r=fresh();r.object('wall',0,1);r.tick(.05);assert(r.chase>0);r.invincible=0;r.object('wall',0,1);r.tick(.05);assert.equal(r.state,'over');});
test('shield and board absorb collision',()=>{for(const k of ['shield','board']){const r=fresh();r.effects[k]=10;r.object('wall',0,1);r.tick(.05);assert.equal(r.effects[k],0);assert.equal(r.chase,0);assert(r.invincible>0);}});
test('board stock consumed exactly once',()=>{const p=C.profile(),r=fresh();assert(r.action('board',p));assert.equal(p.boards,2);assert.equal(r.action('board',p),false);assert.equal(p.boards,2);});
test('magnet collects across all lanes',()=>{const r=fresh();r.effects.magnet=10;for(const lane of [-1,0,1])r.object('coin',lane,8,{y:1});r.tick(.016);assert.equal(r.coins,3);});
test('all pickups apply correct duration',()=>{for(const k of ['magnet','shield','jet','boots','double']){const r=fresh();r.object(k,0,1);assert(r.tick(.05).includes(k));assert.equal(r.effects[k],C.POWERS[k].duration);}});
test('flight avoids obstacles and expires safely',()=>{const r=fresh();r.effects.jet=.1;r.object('wall',0,1);r.tick(.05);assert.equal(r.chase,0);r.tick(.05);assert(r.invincible>0);});
test('boots jump higher and score doubles',()=>{const r=fresh();r.effects.boots=10;r.action('jump');assert.equal(r.vy,14.5);r.effects.double=10;r.tick(.05);assert.equal(r.score,r.distance*2);});
test('ramp reaches train roof without collision',()=>{const r=fresh();r.object('ramp',0,12);r.object('train',0,21.5);let max=0;for(let i=0;i<100;i++){r.tick(.016);max=Math.max(max,r.y);}assert.equal(max,2.7);assert.equal(r.chase,0);});
test('settlement is idempotent and updates missions',()=>{const p=C.profile(),r=fresh();r.distance=1200;r.coins=90;r.score=1500;r.stats.jumps=22;r.stats.powers=5;assert(r.settle(p));assert.equal(r.settle(p),false);assert.equal(p.coins,90);assert.equal(p.runs,1);assert.equal(p.daily.distance,1200);assert.equal(p.history.length,1);assert(C.claim(p,'daily-distance'));assert.equal(C.claim(p,'daily-distance'),false);assert.equal(p.coins,190);});
test('shop cannot overdraw and ownership persists',()=>{const p=C.profile();assert.equal(C.purchase(p,1),false);p.coins=500;assert(C.purchase(p,1));assert.equal(p.coins,350);assert(C.purchase(p,1));assert.equal(p.coins,350);assert(C.buyBoards(p));assert.equal(p.boards,6);assert(C.profile(JSON.parse(JSON.stringify(p))).owned.includes(1));});
test('spawn keeps one safe lane and objects stay bounded',()=>{const r=fresh();r.spawn();const blocked=new Set(r.objects.filter(o=>['train','low','bar','wall'].includes(o.type)).map(o=>o.lane));assert.equal(blocked.size,2);for(let i=0;i<20000;i++){r.effects.jet=10;r.tick(.016);}assert(r.objects.length<100);});
console.log(count+' checks passed');
