
(()=>{
'use strict';
const C=NaiwaCore,$=id=>document.getElementById(id),fmt=n=>Math.floor(n).toLocaleString('zh-CN');
const symbols={home:'⌂',globe:'◎',shirt:'♧',flag:'⚑',bolt:'ϟ',trophy:'♜',settings:'⚙',coin:'●',volume:'♫',help:'?',sun:'☀',users:'♟',spark:'✦',play:'▶',pause:'Ⅱ',arrow:'←',close:'×',shield:'◇',magnet:'∩',rocket:'↗',shoe:'➜',star:'★',board:'▰',building:'▥',flower:'✿',temple:'♜',palm:'♧',snow:'❄',leaf:'❧',hand:'↔',bulb:'☼',alert:'!'};
function icon(k){return '<svg viewBox="0 0 24 24" aria-hidden="true"><text x="12" y="18" text-anchor="middle" fill="currentColor" font-size="21" font-family="Arial,sans-serif">'+(symbols[k]||'✦')+'</text></svg>';}
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(e=>{if(e.tagName==='BUTTON'){if(!e.querySelector('svg'))e.insertAdjacentHTML('afterbegin',icon(e.dataset.icon));}else e.innerHTML=icon(e.dataset.icon);});}
let raw={};try{raw=JSON.parse(localStorage.getItem('naiwa-v2-profile')||'{}');}catch(e){}
let p=C.profile(raw),run=new C.Run(),scene,page='home',audio,toastTimer;
const save=()=>{try{localStorage.setItem('naiwa-v2-profile',JSON.stringify(p));}catch(e){toast('存储不可用，本次进度仅保留到关闭页面。');}refresh();};
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600);}
function tone(f=660){if(!p.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.035*p.volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.13);}catch(e){}}
function refresh(){C.refreshDay(p);$('wallet').textContent=fmt(p.coins);$('bestValue').textContent=fmt(p.best);$('outfitName').textContent=C.SKINS[p.skin].name;$('challengeFill').style.width=Math.min(100,p.daily.distance/10)+'%';$('challengeProgress').textContent=fmt(Math.min(1000,p.daily.distance))+' / 1,000 m';$('soundButton').style.opacity=p.sound?'1':'.4';const m=C.MAPS[p.map];$('mapName').textContent=m.name;$('mapTag').textContent=m.tag;$('mapCountry').textContent=m.country;$('mapNumber').textContent=String(Number(p.map)+1).padStart(2,'0')+' / 10';}
function dialog(html){$('dialogBody').innerHTML=html;icons($('dialogBody'));if(!$('dialog').open)$('dialog').showModal();requestAnimationFrame(()=>{const first=$('dialogBody').querySelector('button');if(first)first.focus();});}
function close(){if($('dialog').open)$('dialog').close();if(run.state==='paused')run.resume();}
function home(){close();if(run.state!=='menu'){run.settle(p);run.reset();save();}document.body.classList.remove('running');$('gameHUD').hidden=true;navigate('home');scene.selectActor('runner');scene.resize();}
function start(){close();navigate('home');scene.selectActor('runner');run.start(p.map);document.body.classList.add('running');$('gameHUD').hidden=false;scene.resize();tone(440);toast('左右换道 · 上跳下滑 · 双击使用滑板');}
function pause(){if(run.state!=='running')return;run.pause();dialog('<p class="eyebrow">游戏暂停</p><h2>暂停</h2><p>已奔跑 '+fmt(run.distance)+' 米，金币 '+run.coins+' 枚。</p><div class="dialog-actions"><button class="start-button" data-do="resume">继续奔跑 ▶</button><button class="outline-button" data-do="home">结算并回大厅</button></div>');}
function over(){run.settle(p);save();dialog('<p class="eyebrow">本局结束</p><h2>本次数据</h2><p>'+C.MAPS[p.map].name+' · 金币已存入钱包</p><div class="result-stats"><div><b>'+fmt(run.distance)+'</b><small>距离 / 米</small></div><div><b>'+fmt(run.score)+'</b><small>积分</small></div><div><b>+'+run.coins+'</b><small>金币</small></div></div><div class="dialog-actions"><button class="start-button" data-do="start">再跑一次 ↗</button><button class="outline-button" data-do="home">返回大厅</button></div>');tone(180);}
function help(){dialog('<p class="eyebrow">操作</p><h2>控制方式</h2><div class="catalog-grid">'+[['左右滑动 / ← →','在三条跑道之间换道'],['上滑 / ↑ / 空格','跳过矮路障'],['下滑 / ↓','滑过高横杆'],['双击 / B','消耗一块滑板，抵挡一次碰撞'],['斜坡与列车','沿斜坡登上车顶，收集高处金币'],['追兵机制','第一次碰撞追兵靠近；7 秒内再次碰撞结束'],['暂停 / Esc','切出页面时也会自动暂停'],['金币与任务','结束后结算金币，任务奖励需手动领取']].map(x=>'<div class="catalog-item"><b>'+x[0]+'</b><p>'+x[1]+'</p></div>').join('')+'</div>');}
const names={home:'奶娃快跑',maps:'世界地图',wardrobe:'奶娃衣橱',missions:'每日任务',powers:'道具工坊',records:'奔跑记录',settings:'游戏设置'};
function navigate(next){page=next;$('homePage').hidden=false;$('contentPage').hidden=next==='home';$('pageName').textContent=names[next];document.querySelectorAll('[data-nav]').forEach(e=>e.classList.toggle('active',e.dataset.nav===next));if(next==='home'){refresh();requestAnimationFrame(()=>{scene&&scene.resize();window.scrollTo({top:0,behavior:'smooth'});});return;}renderPage();requestAnimationFrame(()=>{$('contentPage').scrollIntoView({behavior:'smooth',block:'start'});$('contentTitle').focus({preventScroll:true});});}
function renderPage(){
 const header={maps:['地图','选择地图','共 10 个场景。'],wardrobe:['衣橱','选择服装','共 12 套配色与配饰，使用金币解锁。'],missions:['任务','每日任务','任务每日更新，完成后领取金币。'],powers:['道具','道具说明','跑道道具自动生效，滑板需要主动使用。'],records:['记录','跑酷记录','显示当前浏览器中的最近 10 局。'],settings:['设置','游戏设置','调整音效、音量和画面质量。']}[page];
 $('contentEyebrow').textContent=header[0];$('contentTitle').textContent=header[1];$('contentDesc').textContent=header[2];let html='';
 if(page==='maps')html='<div class="cards-grid">'+C.MAPS.map((m,i)=>'<article class="destination"><div class="map-art" style="--sky:#'+m.sky.toString(16).padStart(6,'0')+';--land:#'+m.ground.toString(16).padStart(6,'0')+';--feature:#'+m.accent.toString(16).padStart(6,'0')+'"><span>'+m.country+'</span>'+icon(m.icon)+'</div><div class="card-body"><h3>'+m.name+'</h3><p>'+m.tag+'</p><div class="card-meta"><span>地图 '+String(i+1).padStart(2,'0')+'</span><button class="mini-btn primary" data-map="'+i+'">'+(p.map===i?'当前目的地':'去这里 ↗')+'</button></div></div></article>').join('')+'</div>';
 if(page==='wardrobe')html='<div class="cards-grid">'+C.SKINS.map((s,i)=>'<article class="destination"><div class="outfit-art" style="--tint:'+s.color+';--accent:'+s.accent+'">'+icon(s.item==='cap'||s.item==='hat'?'users':'shirt')+'<span>套装 '+String(i+1).padStart(2,'0')+'</span></div><div class="card-body"><h3>'+s.name+'</h3><p>'+(p.owned.includes(i)?'已拥有':'解锁后永久保留')+'</p><div class="card-meta"><span>'+(p.owned.includes(i)?'你的衣橱':s.price+' 金币')+'</span><button class="mini-btn primary" data-skin="'+i+'">'+(p.skin===i?'已穿戴':p.owned.includes(i)?'穿戴':'解锁')+'</button></div></div></article>').join('')+'</div>';
 if(page==='missions'){C.refreshDay(p);html='<div class="mission-list">'+C.MISSIONS.map(m=>{const done=p.daily.claimed.includes(m.id),v=Math.min(m.goal,p.daily[m.key]);return '<article class="mission"><i>'+icon('flag')+'</i><div class="mission-main"><h3>'+m.name+'</h3><p>'+m.desc+'</p><div class="progress"><i style="width:'+v/m.goal*100+'%"></i></div><small>'+fmt(v)+' / '+fmt(m.goal)+'</small></div><button class="mini-btn primary" data-claim="'+m.id+'" '+(done||v<m.goal?'disabled':'')+'>'+(done?'已领取':'领取 +'+m.reward)+'</button></article>';}).join('')+'</div>';}
 if(page==='powers')html='<div class="page-banner"><div><b>滑板补给站</b><small>现有 '+p.boards+' 块 · 开跑后按 B 或双击使用</small></div><button class="mini-btn primary" data-do="buyboards">100 金币 / 3 块</button></div><div class="cards-grid">'+Object.entries(C.POWERS).map(([k,v])=>'<article class="power-detail"><div class="power-visual" style="color:'+v.color+'">'+icon(v.icon)+'</div><h3>'+v.name+'</h3><p>'+v.description+'</p><small>'+(k==='board'?'主动使用 · 消耗库存':'跑道拾取 · 即刻生效')+'</small></article>').join('')+'</div>';
 if(page==='records')html='<div class="stat-grid">'+[['最远距离',fmt(p.best)+' m'],['最高积分',fmt(p.bestScore)],['累计奔跑',fmt(p.runs)+' 次'],['收集金币',fmt(p.totalCoins)]].map(x=>'<div class="stat-tile"><small>'+x[0]+'</small><h2>'+x[1]+'</h2></div>').join('')+'</div><div class="settings-box">'+(p.history.length?p.history.map((h,i)=>'<div class="record-row"><span>#'+(i+1)+'　'+C.MAPS[h.map].name+'<small>'+new Date(h.date).toLocaleString('zh-CN')+'</small></span><b>'+fmt(h.distance)+' m</b><span>+'+h.coins+' 金币</span></div>').join(''):'<div class="setting-row">还没有足迹，去跑出你的第一条记录吧。</div>')+'</div>';
 if(page==='settings')html='<div class="settings-box"><div class="setting-row"><span>游戏音效<small>金币与操作提示音</small></span><button class="mini-btn" data-do="sound">'+(p.sound?'已开启':'已关闭')+'</button></div><div class="setting-row"><span>音量</span><input aria-label="音量" id="volumeRange" type="range" min="0" max="1" step=".05" value="'+p.volume+'"></div><div class="setting-row"><span>画面质量<small>流畅模式降低分辨率并关闭阴影</small></span><button class="mini-btn" data-do="quality">'+(p.quality==='high'?'高清':'流畅')+'</button></div><div class="setting-row"><span>操作指南</span><button class="mini-btn" data-open="help">查看</button></div><div class="setting-row"><span>本机存档<small>金币、衣橱、任务和记录保存在此浏览器</small></span><button class="mini-btn" data-do="resetask">重置</button></div></div>';
 $('contentBody').innerHTML=html;icons($('contentBody'));
}
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a.wordmark');if(!b)return;
 if(b.matches('a.wordmark')){e.preventDefault();navigate('home');return;}
 if(b.dataset.nav){navigate(b.dataset.nav);return;}if(b.dataset.open){b.dataset.open==='help'?help():navigate(b.dataset.open);return;}
 if(b.dataset.map!==undefined){p.map=+b.dataset.map;scene.setTheme(p.map);save();navigate('home');return;}
 if(b.dataset.skin!==undefined){if(C.purchase(p,+b.dataset.skin)){scene.setSkin(p.skin);save();navigate('home');toast('已穿戴 · '+C.SKINS[p.skin].name);}else toast('金币不足，先去跑一局吧。');return;}
 if(b.dataset.claim){if(C.claim(p,b.dataset.claim)){save();renderPage();tone(880);toast('任务奖励已存入钱包');}return;}
 if(b.dataset.action){action(b.dataset.action);return;}
 const a=b.dataset.do;if(a==='resume')close();if(a==='home')home();if(a==='start')start();if(a==='buyboards'){if(C.buyBoards(p)){save();renderPage();toast('已补充 3 块滑板');}else toast('需要 100 金币，继续加油！');}
 if(a==='sound'){p.sound=!p.sound;save();if(page==='settings')renderPage();}if(a==='quality'){p.quality=p.quality==='high'?'low':'high';scene.setQuality(p.quality);save();renderPage();}
 if(a==='resetask')dialog('<h2>清空本机存档？</h2><p>这将删除金币、衣橱、任务与奔跑记录，无法撤销。</p><div class="dialog-actions"><button class="outline-button" data-do="cancel">保留存档</button><button class="mini-btn" data-do="reset">确认清空</button></div>');
 if(a==='cancel')close();if(a==='reset'){p=C.profile();scene.setSkin(0);scene.setTheme(0);save();close();navigate('home');toast('已开始新的旅程');}
});
document.addEventListener('input',e=>{if(e.target.id==='volumeRange'){p.volume=+e.target.value;save();}});
$('startButton').onclick=start;$('pauseButton').onclick=pause;$('boardButton').onclick=()=>action('board');$('closeDialog').onclick=()=>{if(run.state==='over')home();else close();};$('dialog').addEventListener('cancel',e=>{e.preventDefault();if(run.state==='over')home();else close();});
$('soundButton').onclick=()=>{p.sound=!p.sound;save();};
$('actorButton').onclick=()=>dialog('<p class="eyebrow">角色</p><h2>角色预览</h2><p>奶娃为玩家角色；碰撞后牛与狗会进入追逐状态。</p><div class="actor-buttons">'+[['runner','奶娃'],['bull','牛牛'],['dog','小狗']].map(x=>'<button class="mini-btn" data-actor="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>');
$('dialogBody').addEventListener('click',e=>{const b=e.target.closest('[data-actor]');if(b){scene.selectActor(b.dataset.actor);close();}});
function action(a){if(run.action(a,p)){if(a==='board'){save();toast('滑板启动 · 可抵挡一次碰撞');}if(a==='jump')tone(400);}else if(a==='board'&&run.state==='running')toast(p.boards?'当前无法使用滑板':'滑板用完了，可在道具工坊补给');}
document.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;const keys={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'jump',ArrowDown:'slide',s:'slide',b:'board',B:'board'};if(run.state==='running'&&keys[e.key]){e.preventDefault();if(!e.repeat)action(keys[e.key]);}if((e.key==='Escape'||e.key==='p')&&!$('dialog').open)pause();});
let down,lastTap=0;$('sceneMount').addEventListener('pointerdown',e=>{if(run.state!=='running')return;down={x:e.clientX,y:e.clientY,time:performance.now()};$('sceneMount').setPointerCapture(e.pointerId);});
$('sceneMount').addEventListener('pointerup',e=>{if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.max(Math.abs(dx),Math.abs(dy))>18)action(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'slide':'jump');else{const now=performance.now();if(now-lastTap<300){action('board');lastTap=0;}else lastTap=now;}down=null;});$('sceneMount').addEventListener('pointercancel',()=>down=null);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>pause());
$('powerCards').innerHTML=['magnet','shield','jet','board'].map(k=>{const v=C.POWERS[k];return '<button class="power-card" data-open="powers"><div class="power-visual" style="color:'+v.color+'">'+icon(v.icon)+'</div><span><strong>'+v.name+'</strong><small>'+v.duration+' 秒 · '+(k==='board'?'主动保护':'跑道拾取')+'</small></span><b>↗</b></button>';}).join('');
icons();refresh();
try{scene=new NaiwaScene($('sceneMount'),p);$('boot').remove();}catch(e){$('bootText').textContent='三维场景加载失败：'+e.message;console.error(e);return;}
let last=performance.now(),hud=0,coinSound=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;const ev=run.tick(dt);for(const e of ev){if(e==='crash')over();else if(e==='chase')toast('追兵靠近！接下来 7 秒保持安全');else if(e.endsWith('-break'))toast('保护已抵挡碰撞');else if(C.POWERS[e]){toast(C.POWERS[e].name+'已启动');tone(950);}else if(e==='coin'&&now-coinSound>100){tone(800);coinSound=now;}}
 if(page==='home')scene.render(run,dt,now/1000);
 if(now-hud>100){hud=now;$('distanceValue').textContent=fmt(run.distance);$('scoreValue').textContent='积分 '+fmt(run.score);$('runCoins').textContent=run.coins;$('speedValue').textContent=Math.floor(run.speed);$('zoneLabel').textContent=C.MAPS[p.map].name;$('boardCount').textContent=p.boards;$('scoreMultiplier').textContent=run.effects.double?'双倍积分 ×2':'距离 / 米';$('chaseHUD').hidden=run.chase<=0;$('powerHUD').innerHTML=Object.entries(run.effects).filter(([k,v])=>v>0).map(([k,v])=>'<div class="effect-pill" style="--accent:'+C.POWERS[k].color+'">'+icon(C.POWERS[k].icon)+'<span>'+C.POWERS[k].name+' <b>'+Math.ceil(v)+'s</b></span></div>').join('');}
}
requestAnimationFrame(frame);window.NaiwaV2={run,get profile(){return p;},start,pause,home,snapshot:()=>({state:run.state,distance:run.distance,coins:run.coins,lane:run.lane,effects:{...run.effects},page,profile:p})};
})();
